# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
#自适应大小，放大和缩小组件都要跟着动
#在self.centralwidget中添加girdLayout，然后在合适的行列中添加widget，然后再添加girdlayout
#在gridlayout添加2x4=8个button
from PyQt5.QtWidgets import QApplication, QSizePolicy

'''
QtWidgets.QWidget()感觉就是在哪个控件上生成一个QWidget，就是父控件和子控件
'''
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 获取显示器分辨率
        self.desktop = QApplication.desktop()
        self.screenRect = self.desktop.screenGeometry()
        self.screenheight = self.screenRect.height()
        self.screenwidth = self.screenRect.width()

        self.height = int(self.screenheight * 0.7)
        self.width = int(self.screenwidth * 0.7)

        #设置大小
        MainWindow.resize(self.width, self.height)
        '''
        QWidget的geometry()提供的成员函数:x()、y()获得客户区左上角的坐标，
        width()、 height()获得客户区的宽度和高度；
        '''
        self.centralwidget = QtWidgets.QWidget()
        #给centralwidget命名
        self.centralwidget.setObjectName("centralwidget")
        self.HLayout =  QtWidgets.QHBoxLayout()
        self.centralwidget.setLocale()
        '''
        QtWidgets.QWidget是PyQt5
        中的一个基类，它提供了构建用户界面的基本元素。可以将QWidget
        理解为窗口或者屏幕上的一块矩形区域，我们可以在这个区域内放置其他控件
        （比如按钮、标签等）以及自定义绘制操作。'''
        self.gridLayoutWidget = QtWidgets.QWidget()
        #QRect类在平面上定义了一个矩形，使用整数作为精度，左上角及宽，高
        #一个矩形正常来说是有一个左上角的点和一个尺寸来确定的
        # self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 270, 1031, 351))
        #以下是为了自适应不同分辨率显示器
        #这里生成Widget
        self.gridLayoutWidget.move(0,self.height*0.6)
        self.gridLayoutWidget.resize(self.width,self.height*0.4)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.HLayout.addWidget(self.gridLayoutWidget)

        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayoutWidget.setLayout(self.gridLayout_2)
        #设置Margins (left,top,right,bottom) 默认白色
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5 = QtWidgets.QPushButton()
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 1, 1, 1)

        # self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6 = QtWidgets.QPushButton()
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 1, 1, 1)

        # self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9 = QtWidgets.QPushButton()
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 2, 1, 1)

        # self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton = QtWidgets.QPushButton()
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)

        # self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)

        # self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3 = QtWidgets.QPushButton()
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)

        # self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8 = QtWidgets.QPushButton()
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 2, 1, 1)

        # self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4 = QtWidgets.QPushButton()
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)

        # self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7 = QtWidgets.QPushButton()
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 2, 1, 1)

        # self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10 = QtWidgets.QPushButton()
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 3, 1, 1)

        # self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11 = QtWidgets.QPushButton()
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 1, 3, 1, 1)

        # self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12 = QtWidgets.QPushButton()
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 3, 1, 1)

        # self.centralwidget.setLayout(self.gridLayout_2)
        #给MainWindow设置中心Widget
        MainWindow.setCentralWidget(self.centralwidget)
        # self.gridLayoutWidget.setLayout(self.gridLayout_2)

        #给MainWindow设置菜单
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        #给MainWindow设置状态bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #调用实例方法，给pushtton设置内容setText()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
